### ISSUE TITLE
Can't switch Grid Charge 1-6 or Gen Charge 1-6 on

### ISSUE THREAD

**Issue by Nurgus** [MorneSaunders360/Solar-Sunsynk#11]
Is there a guide for all the options the service can control? What does mondayOn do for example? There's nothing in the official UI that seems to correspond.

I'm using this in a script. It changes the other settings but the time1on true/false options (including 1 to 6) don't take effect. The existing settings remain.

cap1 to cap6 do take effect.

```
sequence:
  - service: solar_sunsynk.set_solar_settings
    data:
      sn: "xxxxx"
      sellTime1: "01:00"
      sellTime2: "05:00"
      sellTime3: "12:30"
      sellTime4: "13:00"
      sellTime5: "17:00"
      sellTime6: "21:00"
      cap1: "20"
      cap2: "20"
      cap3: "20"
      cap4: "20"
      cap5: "20"
      cap6: "20"
      time1on: false
      time2on: true
      time3on: true
      time4on: false
      time5on: false
      time6on: false
      sysWorkMode: "2"
```
