### ISSUE TITLE
Setting grid charge settings

### ISSUE THREAD

**Issue by tfitzjohn** [MorneSaunders360/Solar-Sunsynk#24]
Hi,

These system settings are fantastic for automating battery dumping or charging -thanks!

One thing - I cannot get the grid charge toggle to turn on. I'm using the following code:
      time5on: true
      sellTime5: "18:03"
      cap5: "100"

**Comment by MorneSaunders360** [comment]
Hi,  

I encountered the same issue when trying to set only one of the `sellTime` values. It turns out that you need to set all of them at once; otherwise, the changes won’t take effect.  

Here’s an example of how it should be configured:  

```json
{
    "time1on": "false",
    "time2on": "false",
    "time3on": "false",
    "time4on": "false",
    "time5on": "true",
    "time6on": "false",
    "sellTime1": "01:00",
    "sellTime2": "05:00",
    "sellTime3": "12:30",
    "sellTime4": "13:00",
    "sellTime5": "8:03",
    "sellTime6": "21:00",
    "cap1": "70",
    "cap2": "70",
    "cap3": "70",
    "cap4": "70",
    "cap5": "100",
    "cap6": "70"
}
```
Let me know if you need any help if the above does not work for you.

**Comment by tfitzjohn** [comment]
/Hi, the times and caps are updating but not the tick boxes

Here's the yaml I'm using (hiding the serial number)

```
action: solar_sunsynk.set_solar_settings
metadata: {}
data:
  sn: "**********"
  time1on: true
  time2on: true
  time3on: true
  time4on: true
  time5on: true
  time6on: true
  sellTime1: "00:00"
  sellTime2: "05:30"
  sellTime3: "12:30"
  sellTime4: "13:00"
  sellTime5: "17:10"
  sellTime6: "23:30"
  cap1: "100"
  cap2: "100"
  cap3: "100"
  cap4: "100"
  cap5: "100"
  cap6: "100"
```
